version: '3.8'
services:
  lab-010:
    image: ubuntu:20.04
    container_name: day-010-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=10
      - LAB_TITLE="Linux Bash Scripts"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
