version: '3.8'
services:
  lab-084:
    image: ubuntu:20.04
    container_name: day-084-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=84
      - LAB_TITLE="Ansible: Copy Files to App Servers"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
