version: '3.8'
services:
  lab-059:
    image: ubuntu:20.04
    container_name: day-059-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=59
      - LAB_TITLE="K8s: Troubleshoot Deployment"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
