version: '3.8'
services:
  lab-020:
    image: ubuntu:20.04
    container_name: day-020-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=20
      - LAB_TITLE="Nginx + PHP-FPM via Unix Socket"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
