version: '3.8'
services:
  lab-021:
    image: ubuntu:20.04
    container_name: day-021-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=21
      - LAB_TITLE="Set Up Git Repository on Storage Server"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
