version: '3.8'
services:
  lab-073:
    image: ubuntu:20.04
    container_name: day-073-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=73
      - LAB_TITLE="Jenkins: Scheduled Jobs"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
