version: '3.8'
services:
  lab-046:
    image: ubuntu:20.04
    container_name: day-046-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=46
      - LAB_TITLE="Multi-container App with Compose"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
