version: '3.8'
services:
  lab-032:
    image: ubuntu:20.04
    container_name: day-032-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=32
      - LAB_TITLE="Git: Rebase"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
