version: '3.8'
services:
  lab-013:
    image: ubuntu:20.04
    container_name: day-013-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=13
      - LAB_TITLE="IPTables Installation and Configuration"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
