version: '3.8'
services:
  lab-015:
    image: ubuntu:20.04
    container_name: day-015-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=15
      - LAB_TITLE="Setup SSL for Nginx"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
