version: '3.8'
services:
  lab-067:
    image: ubuntu:20.04
    container_name: day-067-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=67
      - LAB_TITLE="K8s: Guest Book App"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
