version: '3.8'
services:
  lab-070:
    image: ubuntu:20.04
    container_name: day-070-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=70
      - LAB_TITLE="Jenkins: User Access"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
