version: '3.8'
services:
  lab-007:
    image: ubuntu:20.04
    container_name: day-007-lab
    command: tail -f /dev/null
    volumes:
      - ./workspace:/workspace
    environment:
      - LAB_DAY=7
      - LAB_TITLE="Linux SSH Authentication"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
